# Generated by Django 2.0.2 on 2018-02-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20180215_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phoneNumber',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
