# Generated by Django 2.0.2 on 2018-02-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_remove_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasscodeVerify',
            fields=[
                ('mobile', models.IntegerField(primary_key=True, serialize=False)),
                ('device_ident', models.CharField(max_length=20)),
                ('passcode', models.CharField(default='0000', max_length=4)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='device_ident',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='token',
            field=models.CharField(default='xyz', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phoneNumber',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
