# Generated by Django 2.0.2 on 2018-02-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_auto_20180216_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='uid',
            field=models.IntegerField(default=0),
        ),
    ]
