# Generated by Django 2.0.2 on 2018-02-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0010_transaction_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='device_ident',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
