# Generated by Django 2.0.2 on 2018-02-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0012_auto_20180220_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phoneNumber',
            field=models.CharField(default=0, max_length=255, unique=True),
        ),
    ]
