# Generated by Django 2.0.2 on 2018-02-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0013_auto_20180220_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='device_ident',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
